load mkl/2017.1 (LD_LIBRARY_PATH)
load CUDNN/5.1.10-cuda_8.0 (LD_LIBRARY_PATH, LIBRARY_PATH, C_INCLUDE_PATH, CPLUS_INCLUDE_PATH)
load intel-opencl/2016 (PATH, LD_LIBRARY_PATH, OPENCL_VENDOR_PATH, OPENCL_INC, OPENCL_LIB)
load python/3.6.0+_ML (PATH, MANPATH, LD_LIBRARY_PATH, C_INCLUDE_PATH, CPLUS_INCLUDE_PATH, PYTHONHOME, PYTHONPATH, THEANO_FLAGS)
W tensorflow/stream_executor/cuda/cuda_driver.cc:590] creating context when one is currently active; existing: 0x1226d50
W tensorflow/stream_executor/cuda/cuda_driver.cc:590] creating context when one is currently active; existing: 0x1299690
W tensorflow/stream_executor/cuda/cuda_driver.cc:590] creating context when one is currently active; existing: 0x129d010
ERROR:tensorflow:Exception in QueueRunner: FIFOQueue '_0_input_producer' is closed.
	 [[Node: input_producer/input_producer_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer, input_producer/limit_epochs)]]

Caused by op 'input_producer/input_producer_EnqueueMany', defined at:
  File "autoencoder_val.py", line 280, in <module>
    tf.app.run()
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "autoencoder_val.py", line 276, in main
    run_training()
  File "autoencoder_val.py", line 185, in run_training
    FLAGS.batch_size, num_epochs=FLAGS.num_epochs)
  File "autoencoder_val.py", line 91, in input_pipeline
    filenames, num_epochs=FLAGS.num_epochs, shuffle=False)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 230, in string_input_producer
    cancel_op=cancel_op)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 162, in input_producer
    enq = q.enqueue_many([input_tensor])
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 367, in enqueue_many
    self._queue_ref, vals, name=scope)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1538, in _queue_enqueue_many_v2
    name=name)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

CancelledError (see above for traceback): FIFOQueue '_0_input_producer' is closed.
	 [[Node: input_producer/input_producer_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer, input_producer/limit_epochs)]]

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.CancelledError: FIFOQueue '_0_input_producer' is closed.
	 [[Node: input_producer/input_producer_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer, input_producer/limit_epochs)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/queue_runner_impl.py", line 234, in _run
    sess.run(enqueue_op)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: FIFOQueue '_0_input_producer' is closed.
	 [[Node: input_producer/input_producer_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer, input_producer/limit_epochs)]]

Caused by op 'input_producer/input_producer_EnqueueMany', defined at:
  File "autoencoder_val.py", line 280, in <module>
    tf.app.run()
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "autoencoder_val.py", line 276, in main
    run_training()
  File "autoencoder_val.py", line 185, in run_training
    FLAGS.batch_size, num_epochs=FLAGS.num_epochs)
  File "autoencoder_val.py", line 91, in input_pipeline
    filenames, num_epochs=FLAGS.num_epochs, shuffle=False)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 230, in string_input_producer
    cancel_op=cancel_op)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 162, in input_producer
    enq = q.enqueue_many([input_tensor])
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 367, in enqueue_many
    self._queue_ref, vals, name=scope)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1538, in _queue_enqueue_many_v2
    name=name)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

CancelledError (see above for traceback): FIFOQueue '_0_input_producer' is closed.
	 [[Node: input_producer/input_producer_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer, input_producer/limit_epochs)]]


ERROR:tensorflow:Exception in QueueRunner: FIFOQueue '_0_input_producer' is closed.
	 [[Node: input_producer/input_producer_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer, input_producer/limit_epochs)]]

Caused by op 'input_producer/input_producer_EnqueueMany', defined at:
  File "autoencoder_val.py", line 280, in <module>
    tf.app.run()
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "autoencoder_val.py", line 276, in main
    run_training()
  File "autoencoder_val.py", line 185, in run_training
    FLAGS.batch_size, num_epochs=FLAGS.num_epochs)
  File "autoencoder_val.py", line 91, in input_pipeline
    filenames, num_epochs=FLAGS.num_epochs, shuffle=False)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 230, in string_input_producer
    cancel_op=cancel_op)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 162, in input_producer
    enq = q.enqueue_many([input_tensor])
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 367, in enqueue_many
    self._queue_ref, vals, name=scope)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1538, in _queue_enqueue_many_v2
    name=name)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

CancelledError (see above for traceback): FIFOQueue '_0_input_producer' is closed.
	 [[Node: input_producer/input_producer_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer, input_producer/limit_epochs)]]

ERROR:tensorflow:Exception in QueueRunner: FIFOQueue '_1_input_producer_1' is closed.
	 [[Node: input_producer_1/input_producer_1_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1, input_producer_1/limit_epochs)]]

Caused by op 'input_producer_1/input_producer_1_EnqueueMany', defined at:
  File "autoencoder_val.py", line 280, in <module>
    tf.app.run()
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "autoencoder_val.py", line 276, in main
    run_training()
  File "autoencoder_val.py", line 185, in run_training
    FLAGS.batch_size, num_epochs=FLAGS.num_epochs)
  File "autoencoder_val.py", line 91, in input_pipeline
    filenames, num_epochs=FLAGS.num_epochs, shuffle=False)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 230, in string_input_producer
    cancel_op=cancel_op)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 162, in input_producer
    enq = q.enqueue_many([input_tensor])
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 367, in enqueue_many
    self._queue_ref, vals, name=scope)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1538, in _queue_enqueue_many_v2
    name=name)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

CancelledError (see above for traceback): FIFOQueue '_1_input_producer_1' is closed.
	 [[Node: input_producer_1/input_producer_1_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1, input_producer_1/limit_epochs)]]

Exception in thread Thread-6:
Traceback (most recent call last):
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.CancelledError: FIFOQueue '_1_input_producer_1' is closed.
	 [[Node: input_producer_1/input_producer_1_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1, input_producer_1/limit_epochs)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/queue_runner_impl.py", line 234, in _run
    sess.run(enqueue_op)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: FIFOQueue '_1_input_producer_1' is closed.
	 [[Node: input_producer_1/input_producer_1_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1, input_producer_1/limit_epochs)]]

Caused by op 'input_producer_1/input_producer_1_EnqueueMany', defined at:
  File "autoencoder_val.py", line 280, in <module>
    tf.app.run()
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "autoencoder_val.py", line 276, in main
    run_training()
  File "autoencoder_val.py", line 185, in run_training
    FLAGS.batch_size, num_epochs=FLAGS.num_epochs)
  File "autoencoder_val.py", line 91, in input_pipeline
    filenames, num_epochs=FLAGS.num_epochs, shuffle=False)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 230, in string_input_producer
    cancel_op=cancel_op)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 162, in input_producer
    enq = q.enqueue_many([input_tensor])
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 367, in enqueue_many
    self._queue_ref, vals, name=scope)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1538, in _queue_enqueue_many_v2
    name=name)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

CancelledError (see above for traceback): FIFOQueue '_1_input_producer_1' is closed.
	 [[Node: input_producer_1/input_producer_1_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1, input_producer_1/limit_epochs)]]


Exception in thread Thread-5:
Traceback (most recent call last):
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.CancelledError: FIFOQueue '_0_input_producer' is closed.
	 [[Node: input_producer/input_producer_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer, input_producer/limit_epochs)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/queue_runner_impl.py", line 234, in _run
    sess.run(enqueue_op)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: FIFOQueue '_0_input_producer' is closed.
	 [[Node: input_producer/input_producer_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer, input_producer/limit_epochs)]]

Caused by op 'input_producer/input_producer_EnqueueMany', defined at:
  File "autoencoder_val.py", line 280, in <module>
    tf.app.run()
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "autoencoder_val.py", line 276, in main
    run_training()
  File "autoencoder_val.py", line 185, in run_training
    FLAGS.batch_size, num_epochs=FLAGS.num_epochs)
  File "autoencoder_val.py", line 91, in input_pipeline
    filenames, num_epochs=FLAGS.num_epochs, shuffle=False)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 230, in string_input_producer
    cancel_op=cancel_op)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 162, in input_producer
    enq = q.enqueue_many([input_tensor])
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 367, in enqueue_many
    self._queue_ref, vals, name=scope)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1538, in _queue_enqueue_many_v2
    name=name)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

CancelledError (see above for traceback): FIFOQueue '_0_input_producer' is closed.
	 [[Node: input_producer/input_producer_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer, input_producer/limit_epochs)]]


ERROR:tensorflow:Exception in QueueRunner: FIFOQueue '_0_input_producer' is closed.
	 [[Node: input_producer/input_producer_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer, input_producer/limit_epochs)]]

Caused by op 'input_producer/input_producer_EnqueueMany', defined at:
  File "autoencoder_val.py", line 280, in <module>
    tf.app.run()
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "autoencoder_val.py", line 276, in main
    run_training()
  File "autoencoder_val.py", line 185, in run_training
    FLAGS.batch_size, num_epochs=FLAGS.num_epochs)
  File "autoencoder_val.py", line 91, in input_pipeline
    filenames, num_epochs=FLAGS.num_epochs, shuffle=False)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 230, in string_input_producer
    cancel_op=cancel_op)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 162, in input_producer
    enq = q.enqueue_many([input_tensor])
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 367, in enqueue_many
    self._queue_ref, vals, name=scope)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1538, in _queue_enqueue_many_v2
    name=name)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

CancelledError (see above for traceback): FIFOQueue '_0_input_producer' is closed.
	 [[Node: input_producer/input_producer_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer, input_producer/limit_epochs)]]

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.CancelledError: FIFOQueue '_0_input_producer' is closed.
	 [[Node: input_producer/input_producer_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer, input_producer/limit_epochs)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/queue_runner_impl.py", line 234, in _run
    sess.run(enqueue_op)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: FIFOQueue '_0_input_producer' is closed.
	 [[Node: input_producer/input_producer_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer, input_producer/limit_epochs)]]

Caused by op 'input_producer/input_producer_EnqueueMany', defined at:
  File "autoencoder_val.py", line 280, in <module>
    tf.app.run()
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "autoencoder_val.py", line 276, in main
    run_training()
  File "autoencoder_val.py", line 185, in run_training
    FLAGS.batch_size, num_epochs=FLAGS.num_epochs)
  File "autoencoder_val.py", line 91, in input_pipeline
    filenames, num_epochs=FLAGS.num_epochs, shuffle=False)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 230, in string_input_producer
    cancel_op=cancel_op)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 162, in input_producer
    enq = q.enqueue_many([input_tensor])
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 367, in enqueue_many
    self._queue_ref, vals, name=scope)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1538, in _queue_enqueue_many_v2
    name=name)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

CancelledError (see above for traceback): FIFOQueue '_0_input_producer' is closed.
	 [[Node: input_producer/input_producer_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer, input_producer/limit_epochs)]]


ERROR:tensorflow:Exception in QueueRunner: FIFOQueue '_1_input_producer_1' is closed.
	 [[Node: input_producer_1/input_producer_1_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1, input_producer_1/limit_epochs)]]

Caused by op 'input_producer_1/input_producer_1_EnqueueMany', defined at:
  File "autoencoder_val.py", line 280, in <module>
    tf.app.run()
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "autoencoder_val.py", line 276, in main
    run_training()
  File "autoencoder_val.py", line 185, in run_training
    FLAGS.batch_size, num_epochs=FLAGS.num_epochs)
  File "autoencoder_val.py", line 91, in input_pipeline
    filenames, num_epochs=FLAGS.num_epochs, shuffle=False)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 230, in string_input_producer
    cancel_op=cancel_op)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 162, in input_producer
    enq = q.enqueue_many([input_tensor])
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 367, in enqueue_many
    self._queue_ref, vals, name=scope)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1538, in _queue_enqueue_many_v2
    name=name)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

CancelledError (see above for traceback): FIFOQueue '_1_input_producer_1' is closed.
	 [[Node: input_producer_1/input_producer_1_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1, input_producer_1/limit_epochs)]]

Exception in thread Thread-10:
Traceback (most recent call last):
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.CancelledError: FIFOQueue '_1_input_producer_1' is closed.
	 [[Node: input_producer_1/input_producer_1_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1, input_producer_1/limit_epochs)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/queue_runner_impl.py", line 234, in _run
    sess.run(enqueue_op)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: FIFOQueue '_1_input_producer_1' is closed.
	 [[Node: input_producer_1/input_producer_1_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1, input_producer_1/limit_epochs)]]

Caused by op 'input_producer_1/input_producer_1_EnqueueMany', defined at:
  File "autoencoder_val.py", line 280, in <module>
    tf.app.run()
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "autoencoder_val.py", line 276, in main
    run_training()
  File "autoencoder_val.py", line 185, in run_training
    FLAGS.batch_size, num_epochs=FLAGS.num_epochs)
  File "autoencoder_val.py", line 91, in input_pipeline
    filenames, num_epochs=FLAGS.num_epochs, shuffle=False)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 230, in string_input_producer
    cancel_op=cancel_op)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 162, in input_producer
    enq = q.enqueue_many([input_tensor])
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 367, in enqueue_many
    self._queue_ref, vals, name=scope)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1538, in _queue_enqueue_many_v2
    name=name)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

CancelledError (see above for traceback): FIFOQueue '_1_input_producer_1' is closed.
	 [[Node: input_producer_1/input_producer_1_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1, input_producer_1/limit_epochs)]]


ERROR:tensorflow:Exception in QueueRunner: FIFOQueue '_6_input_producer_2' is closed.
	 [[Node: input_producer_2/input_producer_2_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_2, input_producer_2/limit_epochs)]]

Caused by op 'input_producer_2/input_producer_2_EnqueueMany', defined at:
  File "autoencoder_val.py", line 280, in <module>
    tf.app.run()
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "autoencoder_val.py", line 276, in main
    run_training()
  File "autoencoder_val.py", line 185, in run_training
    FLAGS.batch_size, num_epochs=FLAGS.num_epochs)
  File "autoencoder_val.py", line 91, in input_pipeline
    filenames, num_epochs=FLAGS.num_epochs, shuffle=False)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 230, in string_input_producer
    cancel_op=cancel_op)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 162, in input_producer
    enq = q.enqueue_many([input_tensor])
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 367, in enqueue_many
    self._queue_ref, vals, name=scope)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1538, in _queue_enqueue_many_v2
    name=name)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

CancelledError (see above for traceback): FIFOQueue '_6_input_producer_2' is closed.
	 [[Node: input_producer_2/input_producer_2_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_2, input_producer_2/limit_epochs)]]

Exception in thread Thread-11:
Traceback (most recent call last):
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.CancelledError: FIFOQueue '_6_input_producer_2' is closed.
	 [[Node: input_producer_2/input_producer_2_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_2, input_producer_2/limit_epochs)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/queue_runner_impl.py", line 234, in _run
    sess.run(enqueue_op)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.CancelledError: FIFOQueue '_6_input_producer_2' is closed.
	 [[Node: input_producer_2/input_producer_2_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_2, input_producer_2/limit_epochs)]]

Caused by op 'input_producer_2/input_producer_2_EnqueueMany', defined at:
  File "autoencoder_val.py", line 280, in <module>
    tf.app.run()
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "autoencoder_val.py", line 276, in main
    run_training()
  File "autoencoder_val.py", line 185, in run_training
    FLAGS.batch_size, num_epochs=FLAGS.num_epochs)
  File "autoencoder_val.py", line 91, in input_pipeline
    filenames, num_epochs=FLAGS.num_epochs, shuffle=False)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 230, in string_input_producer
    cancel_op=cancel_op)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/training/input.py", line 162, in input_producer
    enq = q.enqueue_many([input_tensor])
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/data_flow_ops.py", line 367, in enqueue_many
    self._queue_ref, vals, name=scope)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1538, in _queue_enqueue_many_v2
    name=name)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/apps/K80/PYTHON/3.6.0+_ML/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

CancelledError (see above for traceback): FIFOQueue '_6_input_producer_2' is closed.
	 [[Node: input_producer_2/input_producer_2_EnqueueMany = QueueEnqueueManyV2[Tcomponents=[DT_STRING], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_2, input_producer_2/limit_epochs)]]


WARNING:tensorflow:From autoencoder_val.py:216: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_6_input_producer_2' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: ReaderReadV2_2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](TFRecordReaderV2_2, input_producer_2)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_6_input_producer_2' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: ReaderReadV2_2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](TFRecordReaderV2_2, input_producer_2)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_0_input_producer' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](TFRecordReaderV2, input_producer)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_1_input_producer_1' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: ReaderReadV2_1 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](TFRecordReaderV2_1, input_producer_1)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_1_input_producer_1' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: ReaderReadV2_1 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](TFRecordReaderV2_1, input_producer_1)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_0_input_producer' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: ReaderReadV2 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](TFRecordReaderV2, input_producer)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_9_input_producer_3' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: ReaderReadV2_3 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](TFRecordReaderV2_3, input_producer_3)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_9_input_producer_3' is closed and has insufficient elements (requested 1, current size 0)
	 [[Node: ReaderReadV2_3 = ReaderReadV2[_device="/job:localhost/replica:0/task:0/cpu:0"](TFRecordReaderV2_3, input_producer_3)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
W tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 5, current size 0)
	 [[Node: batch = QueueDequeueManyV2[component_types=[DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch/fifo_queue, batch/n)]]
